version: 2.1

jobs:
  test:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    resource_class: medium
    steps:
      - checkout
      - run: pip install uv==0.9.25
      - run: uv sync --python << parameters.python-version >>
      - run: uv run ruff check
      - run: uv run pyrefly check
      - run: uv run pytest

  publish:
    docker:
      - image: cimg/python:3.14
    resource_class: medium
    steps:
      - checkout
      - run: pip install uv==0.9.25
      - run: uv build
      - run: uv publish

  release:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - run: npm i semantic-release@25.0.2 conventional-changelog-conventionalcommits@9.1.0
      - run: npx semantic-release

workflows:
  ci:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.11", "3.14"]
      - release:
          requires:
            - test
          filters:
            branches:
              only: main
  cd:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.11", "3.14"]
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
